export const feedsData = [
  {
    id: 1,
    logo: "L",
    topicContent: "r/Luffy",
    heading: "Kaizoku ou ni ore wa naru",
    img: "../../../components/reddit/img/luffy.jpg",
    commentCount: 2,
    like: "600",
    comment: [
      {
        logo: "A",
        topic: "Aayush",
        body: "You Won't",
        upvote: "150",
      },
      {
        logo: "Z",
        topic: "Zoro",
        body: "I will help you my man",
        upvote: "150",
      },
    ],
  },
  {
    id: 2,
    logo: "Z",
    topicContent: "r/Zoro",
    heading: "Scars on the back are a swordsman's shame",
    img: "../../../components/reddit/img/zoro.jpg",
    commentCount: 2,
    like: "700",
    comment: [
      {
        logo: "L",
        topic: "Luffy",
        body: "I will Help You",
        upvote: "150",
      },
      {
        logo: "S",
        topic: "Sanji",
        body: "Yeah, Right",
        upvote: "150",
      },
    ],
  },
  {
    id: 3,
    logo: "N",
    topicContent: "r/Naruto",
    heading: "Watashi wa hokage ni naru",
    img: "../../../components/reddit/img/naruto.jpg",
    commentCount: 2,
    like: "500",
    comment: [
      {
        logo: "S",
        topic: "Sasuke",
        body: "Naruto",
        upvote: "150",
      },
      {
        logo: "H",
        topic: "Hinata",
        body: "Naruto Kun",
        upvote: "800",
      },
    ],
  },
  {
    id: 4,
    logo: "B",
    topicContent: "r/Batman",
    heading: "World only makes sense if you force it to",
    img: "../../../components/reddit/img/bat.jpg",
    commentCount: 1,
    like: "450",
    comment: [
      {
        logo: "B",
        topic: "Batman Forever",
        body: "I am Vengence, I am the Knight, I am Batman",
        upvote: "800",
      },
    ],
  },
  {
    id: 5,
    logo: "M",
    topicContent: "r/Maskman",
    heading: "No one cared until I started wearing mask",
    img: "../../../components/reddit/img/pexels-photo-1097456 (1).jpg",
    commentCount: 1,
    like: "400",
    comment: [
      {
        logo: "J",
        topic: "Joker",
        body: "Why so serious?",
        upvote: "800",
      },
    ],
  },
  {
    id: 6,
    logo: "A",
    topicContent: "r/ManchesterUnited",
    heading: "Manchester United #ggmu",
    img: "../../../components/reddit/img/man.jpg",
    commentCount: 1,
    like: "600",
    comment: [
      {
        logo: "S",
        topic: "Sir Alex Ferguson",
        body: "Glory Glory Man United #ggmu",
        upvote: "999",
      },
    ],
  },
  {
    id: 7,
    logo: "O",
    topicContent: "r/OnePiece",
    heading: "One Piece is Real",
    img: "../../../components/reddit/img/onepiece.jpeg",
    commentCount: 1,
    like: "401",
    comment: [
      {
        logo: "W",
        topic: "Whitebeard",
        body: "Not Interested!",
        upvote: "800",
      },
    ],
  },
];
